Clock
LaunchCodeLiftoffProjects/workforce-management-app pull request #10
Opened 2019-11-05 15:13 UTC by PetrichorANDphosphenes

time clock beginnings

2019-11-06 01:40 UTC, adahathome requested changes

2019-11-06 01:40 UTC, adahathome commented on src/main/java/org/launchcode/workforce/model/TimeStamp.java
> +    @Column(name = "tid")
just call this column id to keep consistent across tables

2019-11-06 01:40 UTC, adahathome commented on src/main/java/org/launchcode/workforce/controller/TimeStampController.java
> +    TimeStamp add(@RequestBody TimeStamp timeStamp) {
consider simpler args coming from the frontend to limit writing javascript (since javascripts is harder).

2019-11-07 18:23 UTC, PetrichorANDphosphenes commented
I don't think it is perfect but I think it is good enough to that it might be able to be used and then improved

2019-11-08 15:48 UTC, adahathome approved these changes
These changes look great!

2019-11-09 22:05 UTC, lindskelsey approved these changes

2019-11-09 22:05 UTC, merged